<a href="https://colab.research.google.com/github/Elensk8/Anal-tica_Neg/blob/main/Reto1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

0. Cargar librerias de trabajo

In [ ]:
import numpy as np #Funciones numéricas para la transformación y análisis de datos
import pandas as pd
from sklearn.preprocessing import LabelEncoder


1. Procedo con la carga de la base de datos.

In [ ]:
BD= '/content/1. BD2_CarCrash_Int.xlsx'
BD=pd.read_excel(BD)


2. Tranformar variable CrashType a valores numéricos

In [ ]:
from sklearn.preprocessing import LabelEncoder

# Crear el objeto LabelEncoder
label_encoder = LabelEncoder()

# Aplicar la transformación y asignarla a la columna original o a una nueva
BD['CrashType_encoded'] = label_encoder.fit_transform(BD['CrashType'])

print(BD)

            ID      County            City  Weekday  Severity  ViolCat  \
0            1   SAN DIEGO       SAN DIEGO        7         1        8   
1            2    HUMBOLDT  UNINCORPORATED        4         1        8   
2            3     VENTURA          OXNARD        2         1       12   
3            4  STANISLAUS  UNINCORPORATED        4         1        1   
4            5   MENDOCINO  UNINCORPORATED        5         1        1   
...        ...         ...             ...      ...       ...      ...   
112655  112656      SHASTA         REDDING        1         0       11   
112656  112657      SHASTA         REDDING        6         1       11   
112657  112658      SHASTA         REDDING        5         0       11   
112658  112659      SHASTA         REDDING        3         0       11   
112659  112660      SHASTA         REDDING        5         1       11   

        ClearWeather  Month CrashType  Highway  Daylight  CrashType_encoded  
0                  0      1      

3. Remplazar la columna CrashType por CrashType_encoded

In [ ]:
BD['CrashType'] = label_encoder.fit_transform(BD['CrashType'])
print(BD)

            ID      County            City  Weekday  Severity  ViolCat  \
0            1   SAN DIEGO       SAN DIEGO        7         1        8   
1            2    HUMBOLDT  UNINCORPORATED        4         1        8   
2            3     VENTURA          OXNARD        2         1       12   
3            4  STANISLAUS  UNINCORPORATED        4         1        1   
4            5   MENDOCINO  UNINCORPORATED        5         1        1   
...        ...         ...             ...      ...       ...      ...   
112655  112656      SHASTA         REDDING        1         0       11   
112656  112657      SHASTA         REDDING        6         1       11   
112657  112658      SHASTA         REDDING        5         0       11   
112658  112659      SHASTA         REDDING        3         0       11   
112659  112660      SHASTA         REDDING        5         1       11   

        ClearWeather  Month  CrashType  Highway  Daylight  CrashType_encoded  
0                  0      1     

In [ ]:
BD.drop(columns=['CrashType_encoded'], inplace=True)
print(BD)

            ID      County            City  Weekday  Severity  ViolCat  \
0            1   SAN DIEGO       SAN DIEGO        7         1        8   
1            2    HUMBOLDT  UNINCORPORATED        4         1        8   
2            3     VENTURA          OXNARD        2         1       12   
3            4  STANISLAUS  UNINCORPORATED        4         1        1   
4            5   MENDOCINO  UNINCORPORATED        5         1        1   
...        ...         ...             ...      ...       ...      ...   
112655  112656      SHASTA         REDDING        1         0       11   
112656  112657      SHASTA         REDDING        6         1       11   
112657  112658      SHASTA         REDDING        5         0       11   
112658  112659      SHASTA         REDDING        3         0       11   
112659  112660      SHASTA         REDDING        5         1       11   

        ClearWeather  Month  CrashType  Highway  Daylight  
0                  0      1          0        0    

4. Variables de interés y definir entradas y salidas

In [ ]:
 #Se cargan las variables de interés
BD=BD[['City','Weekday','ViolCat','ClearWeather','Month','CrashType','Highway','Daylight']]

#Separamos las variables por Entrada-Salida

XD=BD[['City','Weekday','ViolCat','ClearWeather','Month','CrashType','Daylight']] #Aquí están las variables de entradas
yd=BD[['Highway']] #Aquí está la variable de referencia

print(BD)

                  City  Weekday  ViolCat  ClearWeather  Month  CrashType  \
0            SAN DIEGO        7        8             0      1          0   
1       UNINCORPORATED        4        8             1      1          0   
2               OXNARD        2       12             1      2          0   
3       UNINCORPORATED        4        1             1      1          0   
4       UNINCORPORATED        5        1             1      1          0   
...                ...      ...      ...           ...    ...        ...   
112655         REDDING        1       11             1      3          6   
112656         REDDING        6       11             1      2          6   
112657         REDDING        5       11             1      5          6   
112658         REDDING        3       11             1      7          6   
112659         REDDING        5       11             1      8          6   

        Highway  Daylight  
0             0         1  
1             1         0  
2  

5. Selecciono solo los datos de San Francisco

In [ ]:
BD_SF = BD[BD['City'] == 'SAN FRANCISCO']
print(BD_SF)
XD=BD_SF[['Weekday','ViolCat','ClearWeather','Month','CrashType','Daylight']]
yD=BD_SF[['Highway']]
print(XD)
print(yD)

                 City  Weekday  ViolCat  ClearWeather  Month  CrashType  \
907     SAN FRANCISCO        7        1             1      3          0   
1580    SAN FRANCISCO        2        9             1      2          0   
1581    SAN FRANCISCO        7        3             1      1          0   
1586    SAN FRANCISCO        7        3             1      3          0   
1587    SAN FRANCISCO        3        3             1      3          0   
...               ...      ...      ...           ...    ...        ...   
112598  SAN FRANCISCO        5       11             1      8          6   
112599  SAN FRANCISCO        5       11             1      3          6   
112600  SAN FRANCISCO        6       10             0      4          6   
112601  SAN FRANCISCO        4       10             1      4          6   
112602  SAN FRANCISCO        5       12             1      2          6   

        Highway  Daylight  
907           1         1  
1580          0         0  
1581          0

6. Implementamos modelo

In [ ]:
from sklearn.naive_bayes import GaussianNB
total_filas = BD_SF.shape[0]
print(f"Total de datos (filas): {total_filas}")

mnb=GaussianNB()
mnb.fit(XD,yD)

#Se obtiene la información del modelo
ct=mnb.class_count_
print("Como estan separados los datos",ct)
print("El total de los datos es",len(XD))
print("Los datos porcentualmente estan divididos:", ct/len(XD))

#Se obtiene la información de los ingresos por categoría
u=mnb.theta_
print("la media de los ingresos por categoria es:\n",u)
std=mnb.var_ #Esto es Varianza
std=np.sqrt(std) #Esto es desviación Estándar
print("la desviacion desviación estandar de los ingresos por categoría es\n:",std)

#Se identifican los valores superiores e inferiores de los ingresos
print("El limite superior de los valores:\n",u+std)
print("El limite inferior de los valores:\n",u-std)

#Para evaluar el accidente
XS=[[5,1,1,3,4,0]]
mnb.predict(XS)

print("La persona con estas características tuvo o no va a tener este accidente:\n",mnb.predict(XS))

Total de datos (filas): 2081
Como estan separados los datos [1580.  501.]
El total de los datos es 2081
Los datos porcentualmente estan divididos: [0.75925036 0.24074964]
la media de los ingresos por categoria es:
 [[3.88417722 7.45696203 0.86265823 4.35189873 3.21772152 0.66265823]
 [3.9261477  4.1497006  0.79840319 6.69461078 2.27744511 0.62075848]]
la desviacion desviación estandar de los ingresos por categoría es
: [[1.95062542 3.52136997 0.34420782 2.3433645  1.87371962 0.47280262]
 [2.01603723 2.16198902 0.40119266 3.44163641 1.05765448 0.48519831]]
El limite superior de los valores:
 [[ 5.83480263 10.978332    1.20686605  6.69526323  5.09144114  1.13546084]
 [ 5.94218494  6.31168962  1.19959585 10.13624719  3.33509959  1.10595679]]
El limite inferior de los valores:
 [[1.9335518  3.93559205 0.51845041 2.00853424 1.3440019  0.18985561]
 [1.91011047 1.98771158 0.39721054 3.25297437 1.21979063 0.13556017]]
La persona con estas características tuvo o no va a tener este accidente:
 [

/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:1408: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(
/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  warnings.warn(


7. Matriz de confusión

In [ ]:
from time import perf_counter_ns
#La matriz de confusión tiene 2 cosas: los datos observados = 0 y 1
#El pronóstico del modelo va a ser = 0 y 1

ydp=mnb.predict(XD) #Hazme el pronóstico de los positivos y negativos

from sklearn.metrics import confusion_matrix
cm=confusion_matrix(yD,ydp)
print(cm)

VN=cm[0,0];FP=cm[0,1];FN=cm[1,0];VP=cm[1,1]

Ex=(VN+VP)/(VN+VP+FN+FP)
print("La exactitud es:", Ex)


TE=(FN+FP)/(VN+VP+FN+FP)
print("La tasa de error es:", TE)

Sen=VP/(VP+FN)
print("La sensibilidad es:", Sen)

Esp=VN/(VN+FP)
print("La especificidad es:",Esp)

pre=(VP)/(VP+FP)
print("La precisión es:",pre)

pren=(VN)/(VN+FN)
print("La presición negativa es:",pren)

[[1365  215]
 [ 224  277]]
La exactitud es: 0.7890437289764536
La tasa de error es: 0.21095627102354636
La sensibilidad es: 0.5528942115768463
La especificidad es: 0.8639240506329114
La precisión es: 0.5630081300813008
La presición negativa es: 0.8590308370044053
